/*
  SQL Assignment
  File: Section_D/joins_queries.sql

  Section D - Joins & Relationships
  Topics Covered:
  • INNER JOIN
  • LEFT JOIN
  • RIGHT JOIN
  • FULL OUTER JOIN
  • Foreign Keys

  Author: Tejas Chaudhari
*/



-- Q19. Display each order along with customer details.
-- Show:
-- order_id, order_date, first_name, last_name, total_amount


SELECT
    o.order_id,
    o.order_date,
    c.first_name,
    c.last_name,
    o.total_amount
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id;

-- Explanation:
-- INNER JOIN returns only matching records
-- present in both tables.



-- Q20. List ALL customers and their orders.
-- Customers without orders should also appear.


SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.status,
    o.total_amount
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
ORDER BY c.customer_id;

-- Explanation:
-- LEFT JOIN returns every customer.
-- If a customer has no orders, order-related columns become NULL.




-- Q21. Display order details using three-table JOIN.
--
-- Show:
-- order_id
-- product_name
-- quantity
-- unit_price
-- discount_pct


SELECT
    o.order_id,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.discount_pct
FROM orders o
INNER JOIN order_items oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON oi.product_id = p.product_id
ORDER BY o.order_id;

-- Explanation:
-- orders
--        |
--        |
--   order_items
--        |
--        |
--     products
--
-- This query combines information from all three related tables.




-- Q22. Difference between
-- LEFT JOIN
-- RIGHT JOIN
-- FULL OUTER JOIN


/*

LEFT JOIN

Returns every record from the LEFT table.

Matching rows are returned from the RIGHT table.

If no match exists,
NULL values are shown.

Example

SELECT *
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id;

------------------------------------------------------

RIGHT JOIN

Returns every record from the RIGHT table.

Matching rows are returned from the LEFT table.

Example

SELECT *
FROM customers c
RIGHT JOIN orders o
ON c.customer_id = o.customer_id;

------------------------------------------------------

Difference

LEFT JOIN
Keeps all rows from LEFT table.

RIGHT JOIN
Keeps all rows from RIGHT table.

------------------------------------------------------

FULL OUTER JOIN

Returns

• Matching rows

PLUS

• Non-matching rows from LEFT table

PLUS

• Non-matching rows from RIGHT table

Example

Customers without orders AND Orders without customers appear together.

Note

MySQL does NOT directly support
FULL OUTER JOIN.

It can be simulated using
LEFT JOIN
UNION
RIGHT JOIN.

*/





-- Q23. Identify all Foreign Keys.Explain what happens if customer_id = 999 is inserted into orders.

/*

Foreign Keys

1.

orders.customer_id

references

customers.customer_id

---------------------------------------------------

2.

order_items.order_id

references

orders.order_id

---------------------------------------------------

3.

order_items.product_id

references

products.product_id

---------------------------------------------------


INSERT INTO orders
VALUES
(
1011,
999,
'2024-09-01',
'Pending',
1200
);

---------------------------------------------------

Expected Result

ERROR
Cannot add or update a child row
Foreign Key Constraint Fails

Reason:
Customer ID 999 does not exist in the customers table.

Foreign Keys maintain following: 
1) Referential Integrity
2) Data Consistency
3)Prevent orphan records

*/


-- Example (Valid Insert)

INSERT INTO orders
VALUES
(
1011,
101,
'2024-09-01',
'Pending',
1200.00
);

-- This succeeds because customer_id = 101 exists.



-- Extra JOIN Practice Queries

-- Customer names with total number of orders

SELECT c.customer_id, c.first_name, c.last_name, COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_orders DESC;



-- Product-wise quantity sold

SELECT p.product_name, SUM(oi.quantity) AS total_quantity_sold
FROM products p
INNER JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC;



-- Revenue generated by each customer

SELECT c.first_name, c.last_name, SUM(o.total_amount) AS total_revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.first_name, c.last_name
ORDER BY total_revenue DESC;


